### ISSUE TITLE
Problem running app

### ISSUE THREAD

**Issue by damirj79** [tobyweston/temperature-machine-ui#1]
Hi,

i have installed npm, node.js, create react app, but it looks like i've made a mistake. All I get is information that app has compiled successfully and it is running on http://localhost:3000. This all looks OK, but all I see when accessing this site is:
Welcome to React

To get started, edit src/App.js and save to reload.

Do you have any instructions on how to install your app. ?

**Comment by tobyweston** [comment]
You may have an older version, try `git pull` to get the latest version.

However, it's the second half of the `temperature-machine` app, so you really need to run the main app up in order to serve the UI data. If you don't you wont see any temperatures or charts.

If you're not interested in developing the UI, just check out and update the [temperature-machine](http://github.com/tobyweston/temperature-machine) project and run it from there. This web-app is bundled as part of the other so you really don't need to worry about this (UI) project unless you want to hack it.

I'll add some stuff to the readme of both projects to clarify.
